name: Deploy to DigitalOcean

on:
  push:
    branches:
      - client-server
      - trungnt
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ vars.KEY }}
          script: |
            export PATH=$PATH:/usr/local/bin
            cd ~/we_wactch

            echo "--- Start Deploying ---"

            # Cập nhật code mới nhất
            git fetch origin client-server
            git reset --hard origin/client-server

            # Build và chạy Docker
            # Thêm --remove-orphans để dọn dẹp các container cũ không còn dùng
            docker compose up -d --build --remove-orphans

            # Dọn dẹp các image rác để tránh đầy ổ cứng VPS
            docker image prune -f

            echo "--- Deployment Finished ---"
